const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {database}=require('./helpers/database.cjs');
const {apply}=require('../sql/migrate');
const service=require('../src/services/training.service');
const input={client_name:'Client',client_address:'Adresse',dog_name:'Setter confié',dog_breed:'Setter anglais',service_label:'Débourrage',start_date:'2026-09-07',end_date:'2026-09-11',start_time:'09:00',end_time:'17:00',weekdays:['1','2','3','4','5'],price:'800',deposit:'240',vat_rate:'0',tax_note:'Mention renseignée par le prestataire',terms:'Conditions convenues'};
test('les empreintes des migrations historiques sont conservées',()=>{
  const {migrations}=require('../sql/migrate');
  const files=migrations();
  assert.equal(files.find(f=>f.name==='20260908090926_release_accounts_billing.sql').checksum,'187d7659ca6c0e6df5450ca6521ecdfc4e7d040a65c5d71a46f407b7d50cc06b');
  assert.equal(files.find(f=>f.name==='20260908090927_release_tenant_guards.sql').checksum,'b9e0b25a19f3b1fe23d5b81ece6a7981f06f8e53e7b9a425753ebfb9e0ab6e89');
});
test('validation des montants, dates et jours',()=>{
  assert.equal(service.cents('240,50'),24050);
  for(const amount of ['12abc','-1','1.123','Infinity']) assert.throws(()=>service.cents(amount));
  assert.throws(()=>service.fields({...input,start_date:'2026-02-30'}));
  assert.throws(()=>service.fields({...input,weekdays:[]}));
  assert.throws(()=>service.fields({...input,deposit:'801'}));
  assert.throws(()=>service.fields({...input,tax_note:''}));
  assert.equal(service.sessionDates(service.fields(input)).length,5);
});
test('devis, acomptes partiels, agenda, factures figées, annulation, remboursements et isolation',async t=>{
  const {engine,client}=await database();t.after(()=>engine.close());await apply(client);
  const db=require('../src/db');t.mock.method(db.pool,'connect',async()=>client);t.mock.method(db,'query',(sql,params)=>client.query(sql,params));
  const [a,b]=(await client.query("INSERT INTO breeder(company_name) VALUES('A'),('B') RETURNING id")).rows.map(r=>r.id);
  const job=await service.create(a,input);
  const count=async()=> (await client.query('SELECT count(*)::int AS n FROM calendar_events WHERE breeder_id=$1 AND training_job_id=$2',[a,job.id])).rows[0].n;
  const pay={kind:'deposit',amount:'100',paid_on:'2026-09-06',method:'Virement',reference:'VIR-1',idempotency_key:randomUUID()};
  await assert.rejects(service.payment(a,job.id,pay),e=>e.status===409);
  await assert.rejects(service.accept(b,job.id,'signé'),e=>e.status===404);
  await service.update(a,job.id,input);
  await service.accept(a,job.id,'Devis signé');assert.equal(await count(),0);
  await assert.rejects(service.update(a,job.id,input),e=>e.status===409);
  await service.payment(a,job.id,pay);assert.equal(await count(),0);
  await service.payment(a,job.id,pay);
  assert.equal((await service.detail(a,job.id)).total.received,10000);
  await assert.rejects(service.payment(a,job.id,{...pay,amount:'120'}),e=>e.status===409);
  await assert.rejects(service.documentData(a,job.id,'deposit-invoice'));
  await service.payment(a,job.id,{...pay,amount:'140',reference:'VIR-2',idempotency_key:randomUUID()});
  assert.equal(await count(),5);
  await service.accept(a,job.id,'signé à nouveau');assert.equal(await count(),5);
  await assert.rejects(service.payment(a,job.id,{...pay,amount:'1',idempotency_key:randomUUID()}));
  const deposit=await service.documentData(a,job.id,'deposit-invoice');
  assert.equal((await service.documentData(a,job.id,'deposit-invoice')).number,deposit.number);
  await assert.rejects(service.documentData(a,job.id,'invoice'));
  await service.payment(a,job.id,{...pay,kind:'balance',amount:'560',reference:'SOLDE',idempotency_key:randomUUID()});
  assert.equal((await service.detail(a,job.id)).total.received,80000);
  await assert.rejects(service.payment(a,job.id,{...pay,kind:'balance',amount:'1',idempotency_key:randomUUID()}));
  await service.close(a,job.id,'completed');
  const invoice=await service.documentData(a,job.id,'invoice');
  assert.equal(invoice.total.received,80000);
  const pdf=await require('../src/services/training-document.service').generate(invoice);assert.equal(pdf.subarray(0,4).toString(),'%PDF');
  await service.close(a,job.id,'cancelled');
  const refund=await service.payment(a,job.id,{...pay,kind:'refund',amount:'100',reference:'REM-1',idempotency_key:randomUUID()});
  const credit=await service.documentData(a,job.id,'credit',refund.id);
  const refund2=await service.payment(a,job.id,{...pay,kind:'refund',amount:'100',reference:'REM-2',idempotency_key:randomUUID()});
  assert.notEqual((await service.documentData(a,job.id,'credit',refund2.id)).number,credit.number);
  assert.equal((await service.documentData(a,job.id,'invoice')).total.received,80000);
  assert.equal((await service.detail(a,job.id)).total.received,60000);
  assert.equal((await client.query("SELECT count(*)::int AS n FROM calendar_events WHERE breeder_id=$1 AND training_job_id=$2 AND status='annule'",[a,job.id])).rows[0].n,5);
  await assert.rejects(service.payment(b,job.id,{...pay,idempotency_key:randomUUID()}),e=>e.status===404);
  await assert.rejects(client.query('INSERT INTO training_payments(breeder_id,job_id,kind,amount_cents,paid_on,method,reference,idempotency_key) VALUES($1,$2,\'deposit\',1,current_date,\'Virement\',\'x\',$3)',[b,job.id,randomUUID()]));
  const zero=await service.create(a,{...input,deposit:'0'});await service.accept(a,zero.id,'signé');
  assert.equal((await service.detail(a,zero.id)).job.status,'confirmed');
  await engine.exec('SET ROLE anon');
  await assert.rejects(client.query('SELECT * FROM training_jobs'));
  await engine.exec('RESET ROLE');
  await engine.exec('SET ROLE authenticated');
  await assert.rejects(client.query('SELECT * FROM training_payments'));
  await engine.exec('RESET ROLE');
});
