<?php
require_once '../includes/helpers.php';
require_login(); csrf_check();
if ($_SERVER['REQUEST_METHOD']==='POST') {
    $kind=post_value('kind');
    if($kind==='heat') db()->prepare('INSERT INTO heats (breeder_id,dog_id,female_id,start_date,end_date,stage,notes) VALUES (:bid,:dog,:female,:start,:end,:stage,:notes)')->execute(['bid'=>breeder_id(),'dog'=>post_value('female_id'),'female'=>post_value('female_id'),'start'=>post_value('start_date'),'end'=>post_value('end_date') ?: null,'stage'=>post_value('stage'),'notes'=>post_value('notes')]);
    if($kind==='mating') db()->prepare('INSERT INTO matings (breeder_id,male_id,female_id,mating_date,method,place,notes) VALUES (:bid,:male,:female,:date,:method,:place,:notes)')->execute(['bid'=>breeder_id(),'male'=>post_value('male_id') ?: null,'female'=>post_value('female_id') ?: null,'date'=>post_value('mating_date'),'method'=>post_value('method'),'place'=>post_value('place'),'notes'=>post_value('notes')]);
    if($kind==='pregnancy') db()->prepare('INSERT INTO pregnancies (breeder_id,mating_id,female_id,start_date,expected_date,due_date,result,notes) VALUES (:bid,:mating,:female,:start,:expected,:due,:result,:notes)')->execute(['bid'=>breeder_id(),'mating'=>post_value('mating_id') ?: null,'female'=>post_value('female_id') ?: null,'start'=>post_value('start_date'),'expected'=>post_value('expected_date') ?: null,'due'=>post_value('due_date') ?: null,'result'=>post_value('result'),'notes'=>post_value('notes')]);
    $_SESSION['flash']='Événement reproduction enregistré.'; redirect('/reproduction.php');
}
$heats=db()->prepare('SELECT h.*, d.name female FROM heats h LEFT JOIN dogs d ON d.id=h.female_id WHERE h.breeder_id=:bid ORDER BY h.start_date DESC');$heats->execute(['bid'=>breeder_id()]);
$matings=db()->prepare('SELECT m.*, ma.name male, fe.name female FROM matings m LEFT JOIN dogs ma ON ma.id=m.male_id LEFT JOIN dogs fe ON fe.id=m.female_id WHERE m.breeder_id=:bid ORDER BY m.mating_date DESC');$matings->execute(['bid'=>breeder_id()]);
render_header('Reproduction'); flash();
?>
<section class="grid2"><div class="card"><h2>Chaleur</h2><form method="post"><input type="hidden" name="_csrf" value="<?= csrf_token() ?>"><input type="hidden" name="kind" value="heat"><label>Femelle<select name="female_id"><?= dogs_options() ?></select></label><label>Début<input type="date" name="start_date"></label><label>Fin<input type="date" name="end_date"></label><label>Phase<input name="stage"></label><label>Notes<textarea name="notes"></textarea></label><button class="btn">Enregistrer</button></form></div><div class="card"><h2>Saillie</h2><form method="post"><input type="hidden" name="_csrf" value="<?= csrf_token() ?>"><input type="hidden" name="kind" value="mating"><label>Mâle<select name="male_id"><?= dogs_options() ?></select></label><label>Femelle<select name="female_id"><?= dogs_options() ?></select></label><label>Date<input type="date" name="mating_date"></label><label>Méthode<input name="method"></label><label>Lieu<input name="place"></label><label>Notes<textarea name="notes"></textarea></label><button class="btn">Enregistrer</button></form></div></section>
<div class="card" style="margin-top:16px"><h2>Historique chaleurs</h2><table><tr><th>Femelle</th><th>Début</th><th>Fin</th><th>Phase</th></tr><?php foreach($heats as $h): ?><tr><td><?= e($h['female']) ?></td><td><?= e($h['start_date']) ?></td><td><?= e($h['end_date']) ?></td><td><?= e($h['stage']) ?></td></tr><?php endforeach; ?></table></div>
<div class="card" style="margin-top:16px"><h2>Historique saillies</h2><table><tr><th>Date</th><th>Mâle</th><th>Femelle</th><th>Méthode</th><th>Lieu</th></tr><?php foreach($matings as $m): ?><tr><td><?= e($m['mating_date']) ?></td><td><?= e($m['male']) ?></td><td><?= e($m['female']) ?></td><td><?= e($m['method']) ?></td><td><?= e($m['place']) ?></td></tr><?php endforeach; ?></table></div>
<?php render_footer(); ?>
