<?php
require_once '../includes/helpers.php';
require_login(); csrf_check();
if ($_SERVER['REQUEST_METHOD']==='POST') {
    db()->prepare("INSERT INTO site_settings (breeder_id,public_slug,headline,description,phone,email,city,accent_color,updated_at) VALUES (:bid,:slug,:headline,:description,:phone,:email,:city,:accent,NOW()) ON CONFLICT (breeder_id) DO UPDATE SET public_slug=EXCLUDED.public_slug, headline=EXCLUDED.headline, description=EXCLUDED.description, phone=EXCLUDED.phone, email=EXCLUDED.email, city=EXCLUDED.city, accent_color=EXCLUDED.accent_color, updated_at=NOW()")->execute(['bid'=>breeder_id(),'slug'=>post_value('public_slug'),'headline'=>post_value('headline'),'description'=>post_value('description'),'phone'=>post_value('phone'),'email'=>post_value('email'),'city'=>post_value('city'),'accent'=>post_value('accent_color','#b88746')]);
    $_SESSION['flash']='Site public mis à jour.'; redirect('/site_builder.php');
}
$stmt=db()->prepare('SELECT * FROM site_settings WHERE breeder_id=:bid');$stmt->execute(['bid'=>breeder_id()]);$s=$stmt->fetch() ?: ['public_slug'=>'elevage-demo','headline'=>'Élevage de chiens de travail','description'=>'Sélection, passion, traçabilité et exigence cynotechnique.','phone'=>'','email'=>'','city'=>'','accent_color'=>'#b88746'];
render_header('Générateur de site web'); flash();
?>
<section class="grid2"><div class="card"><h2>Paramètres du site public</h2><form method="post"><input type="hidden" name="_csrf" value="<?= csrf_token() ?>"><label>Slug public<input name="public_slug" value="<?= e($s['public_slug']) ?>" required></label><label>Titre principal<input name="headline" value="<?= e($s['headline']) ?>"></label><label>Description<textarea name="description"><?= e($s['description']) ?></textarea></label><label>Téléphone<input name="phone" value="<?= e($s['phone']) ?>"></label><label>Email<input name="email" value="<?= e($s['email']) ?>"></label><label>Ville<input name="city" value="<?= e($s['city']) ?>"></label><label>Couleur accent<input name="accent_color" value="<?= e($s['accent_color']) ?>"></label><div class="actions"><button class="btn">Publier</button><a class="btn secondary" target="_blank" href="/public_site.php?e=<?= e($s['public_slug']) ?>">Voir le site</a></div></form></div><div class="card"><h2>Fonctionnement</h2><p class="muted">Le générateur publie automatiquement une vitrine avec présentation de l’élevage, chiens actifs et chiots disponibles. Il exploite les données déjà saisies dans le back-office.</p></div></section>
<?php render_footer(); ?>
