const selectionModulesEnabled = process.env.ENABLE_SELECTION_MODULES === 'true';
const aiSelectionAgentEnabled = process.env.ENABLE_AI_SELECTION_AGENT !== 'false';

const allModuleGroups = [
  { key: 'pilotage', labelKey: 'groups.pilotage' },
  { key: 'cheptel', labelKey: 'groups.cheptel' },
  { key: 'sante', labelKey: 'groups.sante' },
  { key: 'structure', labelKey: 'groups.structure' },
  { key: 'reproduction', labelKey: 'groups.reproduction' },
  { key: 'commercial', labelKey: 'groups.commercial' },
  { key: 'selection', labelKey: 'groups.selection' },
  { key: 'communication', labelKey: 'groups.communication' },
  { key: 'admin', labelKey: 'groups.admin' },
];

const allModules = [
  {
    key: 'dashboard',
    labelKey: 'nav.dashboard',
    descriptionKey: 'modules.dashboard.description',
    href: '/dashboard',
    icon: 'dashboard',
    group: 'pilotage',
    accent: 'gold',
  },
  {
    key: 'calendar',
    labelKey: 'nav.calendar',
    descriptionKey: 'modules.calendar.description',
    href: '/calendar',
    icon: 'calendar_month',
    group: 'pilotage',
    accent: 'gold',
  },
  {
    key: 'dogs',
    labelKey: 'nav.dogs',
    descriptionKey: 'modules.dogs.description',
    href: '/dogs',
    icon: 'pets',
    group: 'cheptel',
    accent: 'blue',
  },
  {
    key: 'dogArchives',
    labelKey: 'nav.dogArchives',
    descriptionKey: 'modules.dogArchives.description',
    href: '/dogs/archives',
    icon: 'inventory_2',
    group: 'cheptel',
    accent: 'slate',
  },
  {
    key: 'soins',
    labelKey: 'nav.soins',
    descriptionKey: 'modules.soins.description',
    href: '/soins',
    icon: 'medical_services',
    group: 'sante',
    accent: 'green',
  },
  {
    key: 'healthTests',
    labelKey: 'nav.healthTests',
    descriptionKey: 'modules.healthTests.description',
    href: '/health-tests',
    icon: 'genetics',
    group: 'sante',
    accent: 'green',
  },
  {
    key: 'reminders',
    labelKey: 'nav.reminders',
    descriptionKey: 'modules.reminders.description',
    href: '/reminders',
    icon: 'notifications_active',
    group: 'sante',
    accent: 'orange',
  },
  {
    key: 'weights',
    labelKey: 'nav.weights',
    descriptionKey: 'modules.weights.description',
    href: '/weights',
    icon: 'monitor_weight',
    group: 'sante',
    accent: 'green',
  },
  {
    key: 'structure',
    labelKey: 'nav.structure',
    descriptionKey: 'modules.structure.description',
    href: '/structure',
    icon: 'domain',
    group: 'structure',
    accent: 'gold',
  },
  {
    key: 'heats',
    labelKey: 'nav.heats',
    descriptionKey: 'modules.heats.description',
    href: '/heats',
    icon: 'water_drop',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'reproductionDashboard',
    labelKey: 'nav.reproduction',
    descriptionKey: 'modules.reproduction.description',
    href: '/reproduction',
    icon: 'hub',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'puppies',
    labelKey: 'nav.puppies',
    descriptionKey: 'modules.puppies.description',
    href: '/puppies',
    icon: 'cruelty_free',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'sales',
    labelKey: 'nav.sales',
    descriptionKey: 'modules.sales.description',
    href: '/sales',
    icon: 'payments',
    group: 'commercial',
    accent: 'gold',
  },
  {
    key: 'profitability',
    labelKey: 'nav.profitability',
    descriptionKey: 'modules.profitability.description',
    href: '/profitability',
    icon: 'query_stats',
    group: 'commercial',
    accent: 'gold',
  },
  {
    key: 'selectionAgent',
    labelKey: 'nav.selectionAgent',
    descriptionKey: 'modules.selectionAgent.description',
    href: '/selection-agent',
    icon: 'neurology',
    group: 'selection',
    accent: 'violet',
  },
  {
    key: 'genetics',
    labelKey: 'nav.genetics',
    descriptionKey: 'modules.genetics.description',
    href: '/genetics/simulator',
    icon: 'biotech',
    group: 'selection',
    accent: 'violet',
  },
  {
    key: 'cynognostic',
    labelKey: 'nav.cynognostic',
    descriptionKey: 'modules.cynognostic.description',
    href: '/cynognostic',
    icon: 'psychology_alt',
    group: 'selection',
    accent: 'violet',
  },
  {
    key: 'strategy',
    labelKey: 'nav.strategy',
    descriptionKey: 'modules.strategy.description',
    href: '/strategy',
    icon: 'account_tree',
    group: 'selection',
    accent: 'violet',
  },
  {
    key: 'website',
    labelKey: 'nav.website',
    descriptionKey: 'modules.website.description',
    href: '/site',
    icon: 'language',
    group: 'communication',
    accent: 'blue',
  },
  {
    key: 'settings',
    labelKey: 'nav.settings',
    descriptionKey: 'modules.settings.description',
    href: '/settings',
    icon: 'settings',
    group: 'admin',
    accent: 'slate',
  },
];

const legacySelectionKeys = new Set(['genetics', 'cynognostic', 'strategy']);
const modules = allModules.filter((module) => {
  if (module.key === 'selectionAgent') return aiSelectionAgentEnabled;
  if (legacySelectionKeys.has(module.key)) return selectionModulesEnabled;
  return true;
});
const moduleGroups = allModuleGroups.filter((group) =>
  modules.some((module) => module.group === group.key),
);

module.exports = {
  moduleGroups,
  modules,
  selectionModulesEnabled,
  aiSelectionAgentEnabled,
};
