const moduleGroups = [
  { key: 'pilotage', labelKey: 'groups.pilotage' },
  { key: 'cheptel', labelKey: 'groups.cheptel' },
  { key: 'sante', labelKey: 'groups.sante' },
  { key: 'reproduction', labelKey: 'groups.reproduction' },
  { key: 'commercial', labelKey: 'groups.commercial' },
  { key: 'selection', labelKey: 'groups.selection' },
  { key: 'communication', labelKey: 'groups.communication' },
  { key: 'admin', labelKey: 'groups.admin' },
];

const modules = [
  {
    key: 'dashboard',
    labelKey: 'nav.dashboard',
    descriptionKey: 'modules.dashboard.description',
    href: '/dashboard',
    icon: '⌂',
    group: 'pilotage',
    accent: 'gold',
  },
  {
    key: 'dogs',
    labelKey: 'nav.dogs',
    descriptionKey: 'modules.dogs.description',
    href: '/dogs',
    icon: 'K9',
    group: 'cheptel',
    accent: 'blue',
  },
  {
    key: 'soins',
    labelKey: 'nav.soins',
    descriptionKey: 'modules.soins.description',
    href: '/soins',
    icon: '+',
    group: 'sante',
    accent: 'green',
  },
  {
    key: 'reminders',
    labelKey: 'nav.reminders',
    descriptionKey: 'modules.reminders.description',
    href: '/reminders',
    icon: '!',
    group: 'sante',
    accent: 'orange',
  },
  {
    key: 'weights',
    labelKey: 'nav.weights',
    descriptionKey: 'modules.weights.description',
    href: '/weights',
    icon: 'g',
    group: 'sante',
    accent: 'green',
  },
  {
    key: 'reproduction',
    labelKey: 'nav.reproduction',
    descriptionKey: 'modules.reproduction.description',
    href: '/reproduction',
    icon: 'R',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'heats',
    labelKey: 'nav.heats',
    descriptionKey: 'modules.heats.description',
    href: '/heats',
    icon: 'H',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'matings',
    labelKey: 'nav.matings',
    descriptionKey: 'modules.matings.description',
    href: '/matings',
    icon: 'M',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'pregnancies',
    labelKey: 'nav.pregnancies',
    descriptionKey: 'modules.pregnancies.description',
    href: '/pregnancies',
    icon: 'G',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'litters',
    labelKey: 'nav.litters',
    descriptionKey: 'modules.litters.description',
    href: '/litters',
    icon: 'P',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'puppies',
    labelKey: 'nav.puppies',
    descriptionKey: 'modules.puppies.description',
    href: '/puppies',
    icon: 'C',
    group: 'reproduction',
    accent: 'rose',
  },
  {
    key: 'sales',
    labelKey: 'nav.sales',
    descriptionKey: 'modules.sales.description',
    href: '/sales',
    icon: '€',
    group: 'commercial',
    accent: 'gold',
  },
  {
    key: 'profitability',
    labelKey: 'nav.profitability',
    descriptionKey: 'modules.profitability.description',
    href: '/profitability',
    icon: 'ROI',
    group: 'commercial',
    accent: 'gold',
  },
  {
    key: 'genetics',
    labelKey: 'nav.genetics',
    descriptionKey: 'modules.genetics.description',
    href: '/genetics/simulator',
    icon: 'DNA',
    group: 'selection',
    accent: 'violet',
  },
  {
    key: 'strategy',
    labelKey: 'nav.strategy',
    descriptionKey: 'modules.strategy.description',
    href: '/strategy',
    icon: 'Σ',
    group: 'selection',
    accent: 'violet',
  },
  {
    key: 'breeder',
    labelKey: 'nav.breeder',
    descriptionKey: 'modules.breeder.description',
    href: '/breeder',
    icon: 'ID',
    group: 'communication',
    accent: 'blue',
  },
  {
    key: 'website',
    labelKey: 'nav.website',
    descriptionKey: 'modules.website.description',
    href: '/site',
    icon: 'WEB',
    group: 'communication',
    accent: 'blue',
  },
  {
    key: 'settings',
    labelKey: 'nav.settings',
    descriptionKey: 'modules.settings.description',
    href: '/settings',
    icon: '⚙',
    group: 'admin',
    accent: 'slate',
  },
];

module.exports = {
  moduleGroups,
  modules,
};
